security:
    password_hashers:
        App\Entity\Users: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost: 15

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        # ğŸ” LOGIN (JWT)
        login:
            pattern: ^/api/login$
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: App\Security\JWTAuthenticationSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # ğŸ” API protÃ©gÃ©e par JWT
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        # ğŸ”“ DEV
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # ğŸ”“ MAIN
        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }